version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
